// Code generated by "stringer -type=SceneObjectState"; DO NOT EDIT.

package data

import "fmt"

const _SceneObjectState_name = "SceneObjectState_DeactiveSceneObjectState_SpawnSceneObjectState_StandbySceneObjectState_Destruct"

var _SceneObjectState_index = [...]uint8{0, 25, 47, 71, 96}

func (i SceneObjectState) String() string {
	if i < 0 || i >= SceneObjectState(len(_SceneObjectState_index)-1) {
		return fmt.Sprintf("SceneObjectState(%d)", i)
	}
	return _SceneObjectState_name[_SceneObjectState_index[i]:_SceneObjectState_index[i+1]]
}
