"template_items":[
    {
        "field":"pigshouse",
        "name":"nice",
        "type":"string",
        "priority":1,
        "desc":"description",
        "unit_name":"farm",
        "help":"help",
        "is_display":true,
        "is_required":false,
        "max":1000,
        "min":20,
        "max_length":100,
        "mix_length":1
    }
]